"""Synthetic (toy) tactical combat simulator for unit tests, CI, and policy unit tests.

This is NOT real DOOM and NOT ViZDoom: encounters, damage, and dice rolls are
generated by seeded Python RNG. Use it for deterministic tests, utility tests,
policy unit tests, and failure injection. Use the ViZDoom integration
(anydecision.games.vizdoom_env) or `anydecision real-doom` for genuine evaluation.
Themed after Classic DOOM (id Software) for flavor only.
"""

from __future__ import annotations

import random
import time
from typing import Any, Dict, List, Optional, Sequence, Tuple
import numpy as np
from pydantic import BaseModel, Field
from rich.box import DOUBLE, HEAVY, ROUNDED
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from anydecision.core.engine import DecisionEngine
from anydecision.core.question import Question
from anydecision.theory.utility import UtilityMatrix

# ASCII Art Scenes for DOOM encounters
ASCII_ENCOUNTERS = {
    "Cyberdemon": r"""
           /\_/\
         =( o.o )=   << CYBERDEMON TOWERING 20FT AHEAD >>
          /     \       [ARM-MOUNTED ROCKET LAUNCHER ARMED]
         (  (X)  )      * THUD * * THUD * * ROAAAR *
        (__)___(__)
    """,
    "Baron of Hell": r"""
         (o)(o)      << BARON OF HELL CHARGING >>
        /  /\  \        [GREEN PLASMA FIREBALLS CHARGING]
       |  |  |  |       * HISS * * CREAK *
        \/    \/
    """,
    "Cacodemon": r"""
        .--------.   << CACODEMON HOVERING IN AIR >>
       /  (O)  (O)\     [ELECTRIC LIGHTNING BOLT SPHERE]
      |     V      |
       \  \====/  /
        '--------'
    """,
    "Imp Swarm": r"""
        /\  /\  /\   << AMBUSH: 3 IMPS HURLING FIREBALLS >>
       (oo)(oo)(oo)     [FLAMES CRACKLING ACROSS CORRIDOR]
        ||  ||  ||
    """,
    "Pinky Demon": r"""
        (\___/)      << PINKY DEMON SPRINTING IN MELEE >>
        / O O \         [RAZOR JAWS SNAPPING AT 3 METERS]
       (   "   )
    """,
}

DOOMGUY_HUD = {
    "healthy": "[ >:D ] GODLIKE (100%)",
    "good":    "[ :D ] HEALTHY (75-99%)",
    "hurt":    "[ :| ] HURT (40-74%)",
    "blood":   "[ D: ] CRITICAL (1-39%)",
    "dead":    "[ X_X ] SLAIN IN BATTLE",
}


class DoomEnemy(BaseModel):
    name: str
    hp: int
    max_hp: int
    damage_per_attack: int
    distance_meters: float
    threat_level: str


class DoomGameState(BaseModel):
    """Snapshot of player condition and combat environment."""
    level_name: str
    turn: int
    health: int
    armor: int
    current_weapon: str
    ammo: Dict[str, int]
    enemies: List[DoomEnemy]
    hazard: Optional[str] = None
    pickup: Optional[str] = None
    ascii_scene: str = ""

    def hud_status(self) -> str:
        if self.health <= 0:
            return DOOMGUY_HUD["dead"]
        elif self.health < 40:
            return DOOMGUY_HUD["blood"]
        elif self.health < 75:
            return DOOMGUY_HUD["hurt"]
        elif self.health < 100:
            return DOOMGUY_HUD["good"]
        return DOOMGUY_HUD["healthy"]


class DoomActionOutcome(BaseModel):
    action: str
    success: bool
    damage_dealt: int
    damage_taken: int
    enemy_killed: bool
    summary: str


class DoomScenarioEnvironment:
    """Simulates real-time tactical combat scenarios for Decision Engine benchmark."""

    def __init__(self, seed: int = 42) -> None:
        self.rng = random.Random(seed)

    def generate_encounter(self, difficulty: str = "medium") -> DoomGameState:
        """Create a randomized authentic DOOM combat encounter."""
        if difficulty == "boss":
            level = "E2M8: Tower of Babel"
            enemy_type = "Cyberdemon"
            enemies = [DoomEnemy(name="Cyberdemon", hp=350, max_hp=350, damage_per_attack=45, distance_meters=18.0, threat_level="LETHAL")]
            hazard = "Explosive Rocket Blast Radius"
            pickup = "Soul Sphere (+100 HP)" if self.rng.random() > 0.3 else None
            weapon = "BFG9000" if self.rng.random() > 0.4 else "Plasma Rifle"
            health = self.rng.randint(65, 95)
        elif difficulty == "hard":
            level = "E1M8: Phobos Anomaly"
            enemy_type = "Baron of Hell"
            enemies = [
                DoomEnemy(name="Baron of Hell #1", hp=160, max_hp=160, damage_per_attack=25, distance_meters=7.0, threat_level="HIGH"),
                DoomEnemy(name="Baron of Hell #2", hp=160, max_hp=160, damage_per_attack=25, distance_meters=12.0, threat_level="HIGH"),
            ]
            hazard = "Acid Floor (-5 HP/sec)"
            pickup = "Medikit (+25 HP)"
            weapon = "Super Shotgun"
            health = self.rng.randint(55, 85)
        else:  # medium
            level = "E1M1: Hangar"
            enemy_type = self.rng.choice(["Imp Swarm", "Pinky Demon", "Cacodemon"])
            if enemy_type == "Imp Swarm":
                enemies = [
                    DoomEnemy(name="Imp #1", hp=50, max_hp=50, damage_per_attack=12, distance_meters=4.0, threat_level="MEDIUM"),
                    DoomEnemy(name="Imp #2", hp=50, max_hp=50, damage_per_attack=12, distance_meters=7.0, threat_level="MEDIUM"),
                ]
            elif enemy_type == "Pinky Demon":
                enemies = [DoomEnemy(name="Pinky Demon", hp=100, max_hp=100, damage_per_attack=18, distance_meters=3.0, threat_level="MEDIUM")]
            else:
                enemies = [DoomEnemy(name="Cacodemon", hp=130, max_hp=130, damage_per_attack=20, distance_meters=8.0, threat_level="HIGH")]

            hazard = "Explosive Toxic Barrel" if self.rng.random() > 0.6 else None
            pickup = "Medikit (+25 HP)" if self.rng.random() > 0.4 else "Box of Shells (+20)"
            weapon = "Super Shotgun" if self.rng.random() > 0.5 else "Shotgun"
            health = self.rng.randint(65, 95)

        ascii_art = ASCII_ENCOUNTERS.get(enemy_type, ASCII_ENCOUNTERS["Baron of Hell"])

        return DoomGameState(
            level_name=level,
            turn=1,
            health=health,
            armor=self.rng.randint(25, 60),
            current_weapon=weapon,
            ammo={"shells": 20, "cells": 100, "rockets": 8, "bullets": 60},
            enemies=enemies,
            hazard=hazard,
            pickup=pickup,
            ascii_scene=ascii_art,
        )

    def create_custom_encounter(
        self,
        level_name: str,
        enemies: List[DoomEnemy],
        weapon: str = "Super Shotgun",
        health: int = 100,
        armor: int = 50,
        pickup: Optional[str] = None,
        hazard: Optional[str] = None,
        ascii_scene: str = "",
    ) -> DoomGameState:
        """Create a custom user-defined DOOM encounter with arbitrary enemies and weaponry."""
        scene = ascii_scene or (ASCII_ENCOUNTERS.get(enemies[0].name, "") if enemies else "")
        return DoomGameState(
            level_name=level_name,
            turn=1,
            health=health,
            armor=armor,
            current_weapon=weapon,
            ammo={"shells": 30, "cells": 120, "rockets": 12, "bullets": 100},
            enemies=enemies,
            hazard=hazard,
            pickup=pickup,
            ascii_scene=scene,
        )

    def execute_action(self, state: DoomGameState, action: str) -> Tuple[DoomGameState, DoomActionOutcome]:
        """Step simulation environment according to the AI's tactical action."""
        new_state = state.model_copy(deep=True)
        new_state.turn += 1

        damage_dealt = 0
        damage_taken = 0
        killed = False
        summary_msg = ""
        act_lower = action.lower()

        primary_target = new_state.enemies[0] if new_state.enemies else None

        # Check for attack or weapon fire
        is_attack = any(w in act_lower for w in ["fire", "shoot", "blast", "attack", "burst", "chainsaw"])
        if is_attack and primary_target:
            # Determine weapon used
            if "bfg" in act_lower or new_state.current_weapon == "BFG9000":
                weapon_used = "BFG9000"
                base_dmg = 320
            elif "super shotgun" in act_lower or new_state.current_weapon == "Super Shotgun":
                weapon_used = "Super Shotgun"
                base_dmg = 150
            elif "rocket" in act_lower or new_state.current_weapon == "Rocket Launcher":
                weapon_used = "Rocket Launcher"
                base_dmg = 175
            elif "plasma" in act_lower or new_state.current_weapon == "Plasma Rifle":
                weapon_used = "Plasma Rifle"
                base_dmg = 105
            elif "chainsaw" in act_lower:
                weapon_used = "Chainsaw"
                base_dmg = 120
            elif "chaingun" in act_lower or new_state.current_weapon == "Chaingun":
                weapon_used = "Chaingun"
                base_dmg = 70
            else:
                weapon_used = new_state.current_weapon
                base_dmg = 80

            damage_dealt = int(base_dmg * self.rng.uniform(0.90, 1.30))
            primary_target.hp -= damage_dealt

            if primary_target.hp <= 0:
                killed = True
                slain_name = primary_target.name
                new_state.enemies.pop(0)
                summary_msg = f"CARNAGE: {slain_name} obliterated into bloody gibs with {weapon_used} ({damage_dealt} DMG)!"
                if not new_state.enemies:
                    summary_msg += " ALL HOSTILES ERADICATED!"
            else:
                summary_msg = f"HIT: Dealt {damage_dealt} DMG to {primary_target.name} ({primary_target.hp} HP remaining)."

            # Counter-attack by remaining enemies if not staggered
            if new_state.enemies:
                staggered = self.rng.random() < 0.40  # 40% chance blast staggers monster
                if not staggered:
                    threat = new_state.enemies[0]
                    damage_taken = int(threat.damage_per_attack * self.rng.uniform(0.5, 0.9))

        elif any(w in act_lower for w in ["dodge", "strafe", "evade"]):
            summary_msg = "TACTICAL STRAFE: Sidestepped behind column; enemy projectile slammed harmlessly into wall!"
            damage_taken = int(self.rng.choice([0, 0, 2]))
            if primary_target:
                primary_target.distance_meters = max(2.5, primary_target.distance_meters - 0.5)

        elif any(w in act_lower for w in ["cover", "barrier", "pillar", "reposition"]):
            summary_msg = "COVER SECURED: Broke line of sight behind blast-resistant bulkhead."
            damage_taken = 0

        elif any(w in act_lower for w in ["pickup", "medikit", "health", "grab", "sphere"]):
            if new_state.pickup and ("Health" in new_state.pickup or "Medikit" in str(new_state.pickup)):
                heal_amt = 30
                new_state.health = min(100, new_state.health + heal_amt)
                summary_msg = f"HEALED: Snatched Medikit! Restored +{heal_amt} HP (Current: {new_state.health}%)."
            elif new_state.pickup and "Soul Sphere" in str(new_state.pickup):
                new_state.health = min(200, new_state.health + 100)
                summary_msg = f"SOUL SPHERE CONSUMED: Supercharged to {new_state.health}% HP!"
            else:
                summary_msg = "SUPPLY RUN: Grabbed spare ammunition and armor shards."
            new_state.pickup = None
            damage_taken = int(self.rng.randint(0, 6))

        else:
            # Universal fallback action
            summary_msg = f"TACTICAL MOVE: Executed '{action}'."
            damage_taken = int(self.rng.randint(0, 8))

        # Apply damage to armor first, then health
        if damage_taken > 0:
            if new_state.armor > 0:
                armor_absorbed = min(new_state.armor, damage_taken // 2)
                new_state.armor -= armor_absorbed
                damage_taken -= armor_absorbed
            new_state.health = max(0, new_state.health - damage_taken)

        outcome = DoomActionOutcome(
            action=action,
            success=new_state.health > 0,
            damage_dealt=damage_dealt,
            damage_taken=damage_taken,
            enemy_killed=killed,
            summary=summary_msg,
        )

        return new_state, outcome


class DoomTacticalAgent:
    """Autonomous AI Agent driven by anydecision Expected Utility runtime."""

    def __init__(self, engine: DecisionEngine) -> None:
        self.engine = engine

    def decide_combat_action(self, state: DoomGameState) -> Tuple[str, Any, float]:
        """Convert game state into typed decision question and compute optimal action via Expected Utility."""
        target = state.enemies[0] if state.enemies else None
        target_name = target.name if target else "target"
        weapon = state.current_weapon

        enemy_desc = ", ".join(f"{e.name} ({e.threat_level} threat, {e.distance_meters:.1f}m away)" for e in state.enemies) if state.enemies else "Area clear"
        prompt_text = (
            f"DOOM COMBAT SITUATION [Turn {state.turn} | {state.level_name}]\n"
            f"Doomguy Status: {state.health}% HP | Armor: {state.armor}%\n"
            f"Equipped Arsenal: {weapon} (Ammo: {state.ammo})\n"
            f"Hostile Contacts: {enemy_desc}\n"
            f"Tactical Environment: Hazard: {state.hazard or 'None'} | Pickup: {state.pickup or 'None'}\n"
            f"Question: What is the optimal tactical decision to maximize survival and destroy hostiles?"
        )

        # Dynamically formulate open situation-based choices (universal, not hardcoded enums)
        choices = [
            f"fire {weapon} directly at {target_name}",
            "side-strafe behind obstacle to evade attack",
            "reposition to high ground cover",
        ]
        if state.pickup:
            choices.append(f"sprint to grab {state.pickup}")
        if target and (target.distance_meters < 5.0 or weapon == "Chainsaw"):
            choices.append(f"chainsaw charge to stagger {target_name}")

        # Construct Decision-Theoretic Expected Utility Matrix
        scenarios = ["vulnerable_enemy_window", "incoming_hostile_projectile", "critical_health_hazard"]
        utility_grid: Dict[str, Dict[str, float]] = {}

        for action in choices:
            utility_grid[action] = {}
            for scenario in scenarios:
                if "fire" in action or "blast" in action:
                    # High utility for attacking: rewards decisive elimination
                    if scenario == "vulnerable_enemy_window":
                        u = 48.0
                    elif scenario == "incoming_hostile_projectile":
                        u = 22.0
                    else:
                        u = 15.0 if state.health > 40 else -10.0
                elif "chainsaw" in action:
                    u = 52.0 if scenario == "vulnerable_enemy_window" else 10.0
                elif "strafe" in action or "dodge" in action:
                    u = 42.0 if scenario == "incoming_hostile_projectile" else 8.0
                elif "cover" in action or "reposition" in action:
                    u = 30.0 if scenario == "incoming_hostile_projectile" else 5.0
                elif "grab" in action or "pickup" in action:
                    u = 58.0 if (state.health < 45 or scenario == "critical_health_hazard") else 14.0
                else:
                    u = 10.0
                utility_grid[action][scenario] = u

        q = Question.choice(
            text=prompt_text,
            choices=scenarios,
        )

        matrix = UtilityMatrix(
            actions=choices,
            states=scenarios,
            matrix=utility_grid,
        )

        t0 = time.perf_counter()
        # Execute decision with adaptive early-exit routing for low latency
        decision = self.engine.decide_adaptive(
            question=q,
            utility_matrix=matrix,
            track_layer_trajectory=True,
        )
        latency_ms = (time.perf_counter() - t0) * 1000.0

        chosen_action = decision.selected_action or choices[0]
        return chosen_action, decision, latency_ms


class DoomCombatBenchmarkRunner:
    """Runs automated DOOM combat simulation episodes and logs decision metrics."""

    @staticmethod
    def run_simulation(
        engine: DecisionEngine,
        num_episodes: int = 5,
        max_turns_per_episode: int = 8,
        difficulty: str = "medium",
        render_console: bool = False,
    ) -> Dict[str, Any]:
        env = DoomScenarioEnvironment()
        agent = DoomTacticalAgent(engine)
        console = Console() if render_console else None

        episodes_survived = 0
        total_kills = 0
        total_damage_dealt = 0
        total_decisions = 0
        latencies = []
        action_counts: Dict[str, int] = {}

        for ep in range(1, num_episodes + 1):
            state = env.generate_encounter(difficulty=difficulty)
            if console:
                console.print(f"\n[bold red]=== DOOM COMBAT EPISODE #{ep}: {state.level_name} ===[/bold red]")
                console.print(f"[bold cyan]{state.ascii_scene}[/bold cyan]")

            for turn in range(1, max_turns_per_episode + 1):
                if state.health <= 0 or not state.enemies:
                    break

                action, dec, lat_ms = agent.decide_combat_action(state)
                latencies.append(lat_ms)
                total_decisions += 1
                action_counts[action] = action_counts.get(action, 0) + 1

                new_state, outcome = env.execute_action(state, action)

                if console:
                    conf = dec.confidence * 100
                    emergence = dec.decision_emergence_layer or 24
                    console.print(
                        f"  Turn {turn:02d} | HUD: {state.hud_status()} | "
                        f"Action: [bold yellow]{action.upper()}[/bold yellow] "
                        f"(EU: {dec.optimal_action_utility:+.1f} | Conf: {conf:.1f}% | L{emergence}) | "
                        f"{outcome.summary}"
                    )

                state = new_state
                if outcome.enemy_killed:
                    total_kills += 1
                total_damage_dealt += outcome.damage_dealt

            if state.health > 0:
                episodes_survived += 1
                if console:
                    if not state.enemies:
                        console.print(f"[bold green]>> EPISODE #{ep} VICTORY: All hostiles eradicated! Doomguy survived with {state.health}% HP! <<[/bold green]")
                    else:
                        console.print(f"[bold green]>> EPISODE #{ep} SURVIVED: Room contested. Doomguy survived with {state.health}% HP! <<[/bold green]")
            else:
                if console:
                    console.print(f"[bold red]>> EPISODE #{ep} FAILED: Doomguy was slain. <<[/bold red]")

        survival_rate = episodes_survived / max(1, num_episodes)
        mean_lat = float(np.mean(latencies)) if latencies else 0.0
        decisions_per_sec = float(1000.0 / max(1e-6, mean_lat))

        return {
            "num_episodes": num_episodes,
            "survival_rate": survival_rate,
            "total_kills": total_kills,
            "total_decisions": total_decisions,
            "mean_latency_ms": mean_lat,
            "decisions_per_second": decisions_per_sec,
            "action_distribution": action_counts,
        }
